### ISSUE TITLE
No image generated with stable diffusion

### ISSUE THREAD

**Issue by snakedye** [ImaginerApp/Imaginer#1]
I tried "cacao flower", "butter cat bot", and "git community guidelines" and get the `memory_efficient_attention() got an unexpected keyword argument 'scale'` error.

![image](https://user-images.githubusercontent.com/49378990/236651461-86ac5dff-5fc9-40e4-a017-bbfde845f4ba.png)

**Comment by MohammadsM** [comment]
I can confirm that.
![Bildschirmfoto vom 2023-05-07 06-12-13](https://user-images.githubusercontent.com/4475328/236654889-662343a5-23c1-4ea0-a919-60c03049cf6e.png)


![Bildschirmfoto vom 2023-05-07 06-07-05](https://user-images.githubusercontent.com/4475328/236654758-e29727af-2f0a-4429-ba99-8d46b17654b1.png)

**Comment by lfom** [comment]
It seems that Imaginer actually use HugginFace, so probably this is the cause:

https://github.com/huggingface/huggingface.js/issues/182

**Comment by SandroS22** [comment]
same error.

**Comment by 0xMRTT** [comment]
https://github.com/huggingface/api-inference-community/commit/7d23aacca34e97fe80c89d9f8c49b26c99897025 has fixed that
