### ISSUE TITLE
App doesn't save config. 

### ISSUE THREAD

**Issue by tazihad** [ImaginerApp/Imaginer#14]
App doesn't save config. Save location is being reset everytime app is start. Some API keys also dissaper after restart app.

**Comment by 0xMRTT** [comment]
what's the app version ?

**Comment by tazihad** [comment]
@0xMRTT 0.2.2 from flathub. Using Kubuntu btw

**Comment by 0xMRTT** [comment]
Imaginer is going to be deprecated and merged with Bavarder, it'll be available in more or less a month.
