### ISSUE TITLE
Anything model does not work

### ISSUE THREAD

**Issue by GamingLegends09** [ImaginerApp/Imaginer#15]
I have selected the anything model and when I try to use it, it says, "Model andite/anything-v4.0 does not exist". This model worked before and now it does not. 
![Screenshot from 2023-06-30 14-55-00](https://github.com/ImaginerApp/Imaginer/assets/47454579/1ec0e10b-7f07-4308-8703-cd0c556a4b6e)

**Comment by 0xMRTT** [comment]
Will be fixed in the next release
