### ISSUE TITLE
Generate multiple images at once

### ISSUE THREAD

**Issue by CHJ85** [ImaginerApp/Imaginer#16]
It'd be nice if this app could generate multiple images at once
Like if you could set the amount of images it generates from the gui.

**Comment by 0xMRTT** [comment]
Like Crayion

**Comment by 0xMRTT** [comment]
Imaginer is going to be deprecated and merged with Bavarder, it'll be available in more or less a month.

**Comment by CHJ85** [comment]
Okay cool. Thanks for the update.
