### ISSUE TITLE
Negative Prompts

### ISSUE THREAD

**Issue by LukeZBaker** [ImaginerApp/Imaginer#2]
Please delete

**Comment by 0xMRTT** [comment]
Why ? 

Delete the issue or the feature?

**Comment by LukeZBaker** [comment]
Sorry for being unclear. I meant for the issue to be deleted/closed as you see fit, not the feature!

Background, I was looking at the code and saw references to Negative Prompts. But there was nothing in the interface about this.

I then updated the flatpak to the latest version, and saw the new option re negative prompt. Hence the issue is redundant :)
