### ISSUE TITLE
Unique Filename By Default

### ISSUE THREAD

**Issue by amarraff** [ImaginerApp/Imaginer#20]
**Is your feature request related to a problem? Please describe.**
When I use Imaginer, I often forget to change the default file name. It is left as the default, bavarder-%d-%b-%Y. This accidentally overwrites an image I've already created with the same default filename, an unintended result. Also, even if you change the default filename to something else, it gets reset when the app re-opens. At least if it kept my own custom name, it'd feel like my fault instead of the app's.

**Describe the solution you'd like**
Add in a way to make each file name unique, perhaps by adding (1), (2), etc. to the end of the file name. It would also be nice to have the user's entered prompt affect the file name. This could be the default behavior, with a tick box to override it and let the user enter a custom filename in the field (the way it currently works).

**Comment by 0xMRTT** [comment]
Imaginer is going to be deprecated and merged with Bavarder, it'll be available in more or less a month.
