### ISSUE TITLE
Rate Limit Reached With No Images Generated

### ISSUE THREAD

**Issue by amarraff** [ImaginerApp/Imaginer#21]
**Describe the bug**
I haven't used imaginer in a while, but it's not letting me generate any images. It shows me the error "Rate limit reached. Please log in or use a HF access token."

**Expected behavior**
Open Imaginer, enter prompt, generate image.

**Screenshots**
![Screenshot from 2024-04-26 07-52-46](https://github.com/ImaginerApp/Imaginer/assets/35876526/21cba957-f566-4769-b8ee-f35e5bc9cae3)

**Environment**
page.codeberg.Imaginer.Imaginer 0.2.2
Environment: X-Cinnamon
Gtk: 4.10.5
Python: 3.10.14
OS: Linux 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024
Providers: ['openai', 'stablediffusion']

**Comment by 0xMRTT** [comment]
Imaginer is going to be deprecated and merged with Bavarder, it'll be available in more or less a month.
