### ISSUE TITLE
Model {x} does not exist

### ISSUE THREAD

**Issue by Vazerthon** [ImaginerApp/Imaginer#3]
Seeing message `model {the mode} does not exist` for everything except OpenAI (which gives an invalid key error as I don't have a key)

![image](https://github.com/ImaginerApp/Imaginer/assets/8657986/f7050428-d1d9-4fd7-9f7d-a55aa1e92967)

Installed via Gnome Software (flathub) on Ubuntu 22.04

**Comment by Vazerthon** [comment]
Currently on v0.1.4

This problem seems to be resolved, the app now shows a spinner.

It doesn't seem to ever output an actual file though, the spinner goes away after a while but no file is ever written out. Happy to raise a new issue for that if you prefer

**Comment by 0xMRTT** [comment]
Did you set the output ?

![image](https://github.com/ImaginerApp/Imaginer/assets/105598867/efb67512-1296-4a60-83a2-57c21032273f)

**Comment by Vazerthon** [comment]
I did. The Stable Diffusion gif here is quite quick as it wasn't the first run. Maybe a network call failing for some reason? Is there a way to run the app and get logs?

![Peek 2023-05-10 12-16-1](https://github.com/ImaginerApp/Imaginer/assets/8657986/82fdf80b-ced8-4f41-b2c3-ab92d7415069)

![Peek 2023-05-10 12-16](https://github.com/ImaginerApp/Imaginer/assets/8657986/1bb47c2a-4570-4f41-a5b0-08a5633a0937)

**Comment by 0xMRTT** [comment]
Try giving bavarder access to your home folder using Flatseal

**Comment by Vazerthon** [comment]
That's done the trick
Now I just need to use it for something ridiculous :laughing: 

Thanks for your help and for the cool app!

![imaginer-batman-eating-a-banana-10-May-2023-14-23-40-stable-diffusion](https://github.com/ImaginerApp/Imaginer/assets/8657986/17710288-74e3-4a86-b568-9de78dffe22e)
