### ISSUE TITLE
Rate limit reached. Please log in or ...

### ISSUE THREAD

**Issue by bugtracker2019** [ImaginerApp/Imaginer#6]
**Describe the bug**
After generating some images with all providers, except OpenAI, no more images can be produced and the following warning is shown: **Rate limit reached. Please log in or use your apiToken**

**To Reproduce**
1. Create multiple images
2. See error

**Expected behavior**
Disable the rate limit or automatically generate random apiTokens to prevent this error.

**Environement**
page.codeberg.Imaginer.Imaginer 0.2.0
Environment: MATE
Gtk: 4.10.3
Python: 3.11.3
OS: Linux 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000
Providers: ['analogdiffusion', 'anything', 'nitrodiffusion', 'openai', 'openjourney', 'portrailplus', 'stablediffusion', 'waifudiffusion']

**Comment by 0xMRTT** [comment]
You can set a token in the preferences for having a bigger rate limit, but this feature is a little bugged in v0.2.0 and you should update to v0.2.1 (when 0.2.1 will hit flathub)

See https://imaginer.codeberg.page/help/huggingface
