### ISSUE TITLE
Image displayed in the wrong window

### ISSUE THREAD

**Issue by Nokse22** [ImaginerApp/Imaginer#8]
**Describe the bug**
If I start a image generation in a window and open another one the image is displayed in the wrong window.

**To Reproduce**
1. Open Imagener
2. Start a image generation
3. Open a new window
4. First image displayed in the second window
5. First window keeps loading

**Expected behavior**
Image generated in the right window

**Environement**
page.codeberg.Imaginer.Imaginer 0.2.2
Environment: GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 6.2.15-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023
Providers: ['stablediffusion']

**Comment by 0xMRTT** [comment]
Linked to #9
