### ISSUE TITLE
Windows scales together

### ISSUE THREAD

**Issue by Nokse22** [ImaginerApp/Imaginer#9]
**Describe the bug**
If I open multiple windows they are scaled together

**To Reproduce**
1. Open Imagener
2. Open new window
3. Scale

**Expected behavior**
Every window should be scaled independently 

**Environement**
page.codeberg.Imaginer.Imaginer 0.2.2
Environment: GNOME
Gtk: 4.10.3
Python: 3.10.6
OS: Linux 6.2.15-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 17:37:39 UTC 2023
Providers: ['stablediffusion']

**Comment by 0xMRTT** [comment]
Oh yeah that's because the size of the window is linked to gettings and windows use the same getting key... I'll fix that soon
